services:
  product-service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    image: product-service
    container_name: product-service
    networks:
      - service-net

  discount-service:
    build:
      context: ./discount_service
      dockerfile: Dockerfile
    image: discount-service
    container_name: discount-service
    networks:
      - service-net

  order-service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    image: order-service
    container_name: order-service
    ports:
      - "8002:8000"
    environment:
      PRODUCT_SERVICE_URL: http://product-service:8000
      DISCOUNT_SERVICE_URL: http://discount-service:8000
      DATABASE_URL: postgres://app:app@db:5432/orders
    depends_on:
      - product-service
      - discount-service
      - db
    networks:
      - service-net

  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d orders"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: orders
    volumes:
      - order-db:/var/lib/postgresql/data
    networks:
      - service-net

networks:
  service-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.10.0/24

volumes:
  order-db:
