services:
  product:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    image: product_service
    container_name: product_service
    ports:
      - "8001:8000"
    networks:
      - service-net

  order:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    image: order_service
    container_name: order_service
    ports:
      - "8002:8000"
    environment:
      PRODUCT_SERVICE_URL: http://product_service:8000
    depends_on:
      - product
    networks:
      - service-net

networks:
  service-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.10.0/24