services:
  product:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    image: product_service
    container_name: product_service
    ports:
      - "8001:8000"
    networks:
      - service-net

  order:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    image: order_service
    container_name: order_service
    ports:
      - "8002:8000"
    environment:
      PRODUCT_SERVICE_URL: http://product_service:8000
      DATABASE_URL: postgres://app:app@db:5432/orders
    depends_on:
      product:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - service-net

  db:
    image: postgres:16
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d orders"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: orders
    volumes:
      - order-db:/var/lib/postgresql/data
    networks:
      - service-net 

networks:
  service-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.10.0/24

volumes:
  order-db: